server:
  port: 8080

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost  # eureka 服务端的实例名称
  client:
    register-with-eureka: false   # 不向注册中心注册自己
    fetch-registry: false         # 自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      #与 eurekaServer 交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:8080/eureka/
