server:
  port: 8080

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/eureka_demo_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
#      server-addr: localhost:8848 # 配置 nacos 服务端地址
      discovery:
        cluster-name: HZ # 配置集群信息
        namespace: public # 命名空间ID
        username: nacos
        password: nacos
        server-addr: localhost:8848 # 配置 nacos 服务端地址

user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 同集群内优先的负载均衡规则

logging:
  level:
    cool.wrp.feignapi.clients: DEBUG